[package]
name = "virtio-gpu-wddm-rs"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bitflags.workspace = true
crossbeam.workspace = true
log.workspace = true
spin.workspace = true
uart_16550.workspace = true
virtio-drivers = { path = "../virtio-drivers", features = ["alloc"], default-features = false }
tagged = { path = "../proc/tagged" }
wdk = { path = "../wdk" }
zerocopy.workspace = true
winresult.workspace = true
ida-rs.workspace = true
pin-init.workspace = true
microseh = { path = "../util/microseh", features = [], default-features = false }
offset-allocator = { path = "../util/offset-allocator" }
#sorted-vec = { path = "../util/sorted-vec" }
smallvec.workspace = true
atomicbox.workspace = true
hashbrown.workspace = true
modular-bitfield.workspace = true
itertools.workspace = true

[build-dependencies]
chrono.workspace = true
ewdk = { path = "../util/ewdk" }
